- hosts: all
  #  vars:
  #    foo: bar 
      
  tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
    
    - name: install deps
      ansible.builtin.apt:
        name: ca-certificates

          #- include: "{{ TASKS_DIR_PLAYS }}set_shecan.yml"

    - name: add apt source for kubernetes(keyring)
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg


    - name: add apt source for kubernetes(apt source)
      shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list


    - name: test apt update
      ansible.builtin.apt:
        update_cache: yes
       

