- hosts: all
  #  vars:
  #    foo: bar 
      
  tasks:


    - name: enable ipv4 routing
      shell: |
        echo "net.ipv4.ip_forward=1" | tee /etc/sysctl.d/10-ip_forward.conf && sysctl -w net.ipv4.ip_forward=1
    
