- hosts: manager1
  vars:
    kubeadm_conf: /etc/kubernetes/kubeadm-config.yaml
      #control_plane_endpoint: api.localkube 
      #pod_network_cidr: 10.244.0.0/16
  tasks:


    - name: initialize control-plane node
      shell: "kubeadm init --config {{ kubeadm_conf  }} " # --control-plane-endpoint {{ control_plane_endpoint }}  --pod-network-cidr {{ pod_network_cidr }}"
    
