- hosts: all
  #  vars:
  #    foo: bar 
      
  tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
    

    - name: install kubelet using apt
      ansible.builtin.apt:
        name: "kubelet={{ K8S_VERSION_APT  }}"
        allow_downgrade: true
        allow_change_held_packages: true

    - name: pin kubelet's version
      shell: |
        apt-mark hold kubelet
    
          #- include: "{{ TASKS_DIR_PLAYS }}set_default_nameservers.yml"
