- hosts: all
  #  vars:
  #    foo: bar 
      
  tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
    
    - name: install deps
      ansible.builtin.apt:
        name: ca-certificates

    - name: install deps
      ansible.builtin.apt:
        name: lsb-release

    - name: install deps
      ansible.builtin.apt:
        name: gnupg

    - name: add apt source for docker
      shell: mkdir -p /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
       
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes

    - name: install containerd using apt
      ansible.builtin.apt:
        name: containerd.io
    
