- hosts: all
  #  vars:
  #    foo: bar 
      
  tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
    
    - name: install kubectl using apt
      ansible.builtin.apt:
        name: "kubectl={{ K8S_VERSION_APT }}"
        allow_downgrade: true
        allow_change_held_packages: true

    
    - name: pin kubectl's version
      shell: |
        apt-mark hold kubectl

          #- include: "{{ TASKS_DIR_PLAYS }}set_default_nameservers.yml"
    
    - name: enable bash completion for kubectl
      shell: |
        kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
