- hosts: all
  #  vars:
  #    foo: bar 
      
  tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes

    - name: install kubeadm using apt
      ansible.builtin.apt:
        name: "kubeadm={{ K8S_VERSION_APT }}"
        allow_downgrade: true
        allow_change_held_packages: true

    - name: pin kubeadm's version
      shell: |
        apt-mark hold kubeadm
    
    - name: enable bash completion for kubeadm
      shell: |
        kubeadm completion bash | tee /etc/bash_completion.d/kubeadm > /dev/null

          #- include: "{{ TASKS_DIR_PLAYS }}set_default_nameservers.yml"
