- hosts: all
  #  vars:
  #    foo: bar 
      
  tasks:

    - name: set custom dns
      shell: | 
        chattr -i /etc/resolv.conf | rm /etc/resolv.conf
        echo "nameserver 192.168.56.20" > /etc/resolv.conf ; echo "nameserver   9.9.9.9" >> /etc/resolv.conf
        chattr +i /etc/resolv.conf

