- hosts: all
  #  vars:
  #    foo: bar 
      
  tasks:

    - name: set shecan dns
      shell: echo "nameserver 178.22.122.100" > /etc/resolv.conf ; echo "nameserver   185.51.200.2" >> /etc/resolv.conf

